name: Build

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
  workflow_dispatch:

env:
  NODE_VERSION: "18.15.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch in repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build
